### ISSUE TITLE
HA Reports Higher Percentage

### ISSUE THREAD

**Issue by tango2590** [spbrogan/sensor.mopeka_pro_check#10]
Ever since I added this integration, there has been discrepancies between what Mopeka has and what HA has. For instance, in the screenshots you will see Driver Side at 32.0% in HA, but 17% on the Mopeka app. The real stinger? The tank is actually empty.

![Screenshot_20220126-234945_Home Assistant](https://user-images.githubusercontent.com/78666662/151300634-598a82ce-149c-426e-8fd8-712a6894c6b0.jpg)
![Screenshot_20220126-235020_Tank ](https://user-images.githubusercontent.com/78666662/151300653-bdaf62d1-8e99-49fb-81ca-407fe2d6e521.jpg)

**Comment by spbrogan** [comment]
Interesting.  I think there are a couple of things going on. 

1. I checked in recent changes to align the two but i never "made a release" so if you are using HACS...and the custom repository then i think i need to do an update. 

2. I would be curious if you could share your "quality" reading.  Should be a number between 0-3.  I have seen as a tank gets low the reading gets really bad and the distance jumps all over.  In the newer version once the reading reaches med-low quality it will just report 0%.  

I am reading now how to update the version.  I don't remember if I just need to Tag the repo / make a github release or what the HACS server is looking for.  I'll respond here once i do that.

**Comment by spbrogan** [comment]
You should now see a version 1.0.0.  This version should have the changes the fix your alignment issues.  
Please open bug if you have version 1.0.0 and still see this problem.
