### ISSUE TITLE
Information's on "Level Value"

### ISSUE THREAD

**Issue by Next9999** [spbrogan/sensor.mopeka_pro_check#14]
Hi

one of the attribute is "Level"... i am trying to understand the value provided

I was thinking to use to value to see if my RV is level :-)
i have contact Mopeka , but they said that Home Assistance was not in scope :-(

tks again and nice work

Having the Propane Level in my Home Assistance is very useful

![image](https://user-images.githubusercontent.com/54117519/159538541-5424a9e0-81ee-490c-b1f1-20262574447e.png)

**Comment by spbrogan** [comment]
I didn't think it was called level in the sensor attributes.  It should be the distance the sensor is reading in mm.  
https://github.com/spbrogan/sensor.mopeka_pro_check/blob/10e0075f7416ce639efc1430b76e58265b8deed9/custom_components/mopeka_pro_check/sensor.py#L217

**Comment by spbrogan** [comment]
hopefully that helps
