### ISSUE TITLE
documentation & "mfg mode"

### ISSUE THREAD

**Issue by mhaberler** [spbrogan/sensor.mopeka_pro_check#17]
Hi @spbrogan 

I'm a tad desperate about getting any documentation on the Mopeka Pro protocol & behaviour

I need to adjust the reporting rate from an application (c++, based on your code) - can you point me to any source of documentation or person at Mopeka which can help?

btw you mention

````
Press the green button on your sensor 10 times quickly to get it out of mfg mode
````

how would that change behaviour? different update rate? 

thanks in advance

Michael

**Comment by spbrogan** [comment]
I don't think you adjust the rate on the device.  It is just a "passive" BLE advertisement.  The information I have seen has nothing about ability to connect to the device over BLE and/or change any parameters.   There is mention in their user manual about mfg mode (and how to wake it up by pressing the green button).   On the "reading side" you could obviously ignore some reads, avg them, filter them, etc.  But that depends on what you are using to read the BLE advertisements.  

As for any docs,  I have heard numerous people getting access to internal information using their support email address.  My suggestion would be to try that.  I think there is someone who has had success with Victron.  
https://community.victronenergy.com/questions/52274/venus-raspberry-pi-read-other-ble-device.html

Additionally, you can ssee C++ code in esphome if that is helpful. 
https://github.com/esphome/esphome/tree/dev/esphome/components/mopeka_pro_check

**Comment by mhaberler** [comment]
thanks, that link is very helpful; I got the decoding already sorted on an esp32

I explored the Pro sensor with nRF Connect and it shows lots of custom characteristics some of which are [mentioned here](https://github.com/Albertworker1004/Mopeka_React-Native/blob/main/Tank%20Check/firmware.md)

this lead me to assume it's configurable after a BLE connection by setting params

using the app you can adjust the update rate from some 3..30 seconds or so, which suggested to me there's a way to interact with the device

but then it might not be necessary after all. Thanks for the hints!

**Comment by spbrogan** [comment]
interesting.  That information wasn't in the document that was shared with me by mopeka support and I have avoided looking at that project in general as I can't tell the origins of that code, if it is authorized, and what license it is using.  Anyway, glad you found what you need.
