### ISSUE TITLE
can't find Mopeka in HACS repositories? :(

### ISSUE THREAD

**Issue by VillaBlanche** [spbrogan/sensor.mopeka_pro_check#23]
Hi guys, been trying to get MOPEKA running but can't find the repository via HACS.
Also, i try to do it manually, however for some reason with SAMBA i can't see 'homassistant' as a network drive and have no CLUE why not.

So i'm currently stuck :-(
And frustrated :-P

Any help would be welcome.

**Comment by VillaBlanche** [comment]
update: i got as far as a manual install.
However the mopeka_pro_check.discovered is not visible in the developer tools services tab.
Is that because of a manual install? i need to activate a service somewhere?

**Comment by VillaBlanche** [comment]
After the manual install, when i open the files through the explorer they seem to be 'emptied'.
I see only empty lines in the files like sensor.py in the \config\custom_components\mopeka_pro_check folder

**Comment by VillaBlanche** [comment]
Another step forward, i edited all files manually and re-copied all the content, then restarted from the terminal console SSH and it kept the content of the files there.
It know recognizes the function like:
mopeka_pro_check: discovered

However i get the error that there is an unexpected error calling this server, so discovery is not working :(

**Comment by spbrogan** [comment]
So I added a discussion about the fact that with latest ha I don't expect this to work anymore. I use esphome to be the gateway between ble and ha. 

I need to rewrite this component using the new support for ble in ha core. 

Sorry for the confusion.  Does the esphome solution help?

Thanks
Sean

**Comment by spbrogan** [comment]
Discussion.  https://github.com/spbrogan/sensor.mopeka_pro_check/discussions/22

Esphome   https://esphome.io/components/sensor/mopeka_pro_check.html

**Comment by VillaBlanche** [comment]
Damn, i didn't see that, i bought a Bluetooth device for my HA server :(
I'm not sure if i can get this to work with the esphome solution.
I have a TTGO T-journal lying around, but does that then mean the esp32 captures the device data and publishes to 
mqtt or something? or how do i get the data in Home Assistant?

**Comment by VillaBlanche** [comment]
Also the sensor will be pretty far away, so i was gonna test if my Bluetooth 5.0 stick with antenna would cover for the distance or not. (gonna be 20 meters away with 3 ytong walls in between.

**Comment by VillaBlanche** [comment]
Is there, for the esp32 solution more information of how to deploy or write to the esp32 device, which codes and which files and configurations to make this work?

**Comment by VillaBlanche** [comment]
Think i got it, it's all through ESPHome in HA. gonna see if this works with my TTGO Tjournal

**Comment by VillaBlanche** [comment]
If you could make a few screenshots on how to set this up for a device, i would really appreciate that, i seem to be stuck already when trying to upload from ESPHOME towards the device, says it's not matching the minimum requirements etc.

As ex developer i'm too often lost these days lol... :)

**Comment by VillaBlanche** [comment]
And issues like this:
Failed to initialize. Try resetting your device or holding the BOOT button while selecting your serial port until it starts preparing the installation.

i do hold the ttgo reset button, either at usb plug in or at connect selection in ESP home, doen't seem to do the trick

**Comment by VillaBlanche** [comment]
couple steps forward, however when trying over the air install it fails at the step to connect to the device IP.
;(
web ui and physical connection failed also...

**Comment by VillaBlanche** [comment]
Was able to install a generated bin file from ESPHOME through my pc, using the espressif flash tool, however when i try to install it from ESPHOME over the air, it won't resolve the -devicename-.local into an api address.
As an error it asks if it's connected to wifi, the settings should have gone through over the bin file though.

again a bit stuck :(
Thanks in advance for any help!

**Comment by VillaBlanche** [comment]
case closed: great success.
Issues with usb2uart recognition of the virtualbox

**Comment by VillaBlanche** [comment]
1 final question though, i saw that on the logs i get data reads every 1 second.
Is there a way to set this towards the mopeka sensor to like 1 time per hour?
seems a bit of a waste of battery to get info every 1 second on a gas tank :-P

**Comment by spbrogan** [comment]
Yeah with ble advertisements reading them or not reading them doesn't change power consumption. I have wondered if the app can connect and write some attribute to the sensor to slow down its reporting but I am not sure. 

ESP just listens and reports each time there is a new advertisement.

**Comment by Varkzor** [comment]
Ok thanks a lot Mr Brogan :)
I have just tested with a Netatmo weather station, which is getting the wifi settings via bluetooth, so i guess it could potentially work with the Mopeka app.
Although when i make the settings in the Mopeka app to 30 seconds, i still get readings every second or so in the logfiles of the device.

**Comment by Varkzor** [comment]
not sure if you still have a contact with Mopeka, could be useful to know if they know how to reduce this drastically.
For me a reading every 30 minutes or so would be more than sufficient :-)

**Comment by spbrogan** [comment]
I have asked Mopeka for an updated specification on their sensor fw and if there are any configuration options.  

I have not heard anything back but agree it would be great.  Hopefully they will respond.
