### ISSUE TITLE
Support esphome bluetooth_proxy

### ISSUE THREAD

**Issue by edestecd** [spbrogan/sensor.mopeka_pro_check#26]
I tried with this and a bluetooth_proxy esp32 dev board with no success.
I suspect some work has to be done here. Willing to do work if pointed in the right direction

**Comment by spbrogan** [comment]
I wrote this up earlier this summer so lets move the conversation over there.  
https://github.com/spbrogan/sensor.mopeka_pro_check/discussions/22
