### ISSUE TITLE
cannot change the "scan_interval"

### ISSUE THREAD

**Issue by Fraenky-dw** [spbrogan/sensor.mopeka_pro_check#28]
I tried to change the scan_interval to 300 but the Homeassistant-Configuration Check told me:

 Invalid config for [sensor.mopeka_pro_check]: expected int for dictionary value @ data['scan_interval']. Got datetime.timedelta(seconds=300). (See ?, line ?). 

Example for my configuration.yaml:
sensor:
  - platform: mopeka_pro_check
    scan_interval: 300
    mopeka_devices:
      - mac: "A1:B2:C3:D4:E5:F6"
        name: RV Right Tank
      - mac: "A6:B5:C4:D3:E2:F1"
        name: RV Left Tank
        tank_type: "standard"
        tank: "20lb_v"
      - mac: "A0:B0:C0:D0:E0:F0"
        name: BBQ
        tank_type: "custom"
        max_height: 452.10
        min_height: 23

**Comment by spbrogan** [comment]
Are you running on a current version of HA?  
In Mid 2022 the HA team started doing a lot of work with BLE and now their integrated work makes things incompatible with this integration.  If the scan interval is the only problem, you are running into I am surprised.   Please see comments here about plans: https://github.com/spbrogan/sensor.mopeka_pro_check/discussions/22

At this moment my suggestion would be to use the esphome integration for now as that works well and is fully supported.  
Thanks

**Comment by spbrogan** [comment]
I also wrote more here: https://github.com/spbrogan/sensor.mopeka_pro_check/issues/27
