### ISSUE TITLE
Not available in HACS

### ISSUE THREAD

**Issue by sergeantbort** [spbrogan/sensor.mopeka_pro_check#4]
I am unable to locate this in HACS.

**Comment by phurth** [comment]
It's not mentioned in the documentation, but you need to add this repository (https://github.com/spbrogan/sensor.mopeka_pro_check) as a custom repository in HACS.

**Comment by sergeantbort** [comment]
> It's not mentioned in the documentation, but you need to add this repository (https://github.com/spbrogan/sensor.mopeka_pro_check) as a custom repository in HACS.

appreciate that!  haven't messed to much with HACS.    

Still can't get it working but at least it's in HACS.. think it might be my bluetooth adapter not seeing any BLE devices.. only seem to be able to see regular bluetooth devices..   Not related but if anyone has a recommendation of a compatible adapter.
